### ISSUE TITLE
bloatware removal

### ISSUE THREAD

**Issue by levolz** [lukekorthals/pips_cheat#1]
Please remove unnecessary files etc. for the poor TA grading your stuff

**Comment by lukekorthals** [comment]
![NoLetMeThinkGIF (2)](https://user-images.githubusercontent.com/55378727/220962669-baeae3a2-e422-4b11-816e-bf1a05b3f895.gif)

**Comment by lukekorthals** [comment]
![NoLetMeThinkGIF](https://user-images.githubusercontent.com/55378727/220962829-5e731a4b-a31b-4c10-bd82-d4ec3072e3c3.gif)
